server:
  port: 8088

spring:
  application:
    name: contract-service
  datasource:
    url: jdbc:postgresql://localhost:5432/contract_db
    username: smartgrid
    password: smartgrid_dev_pw
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/.well-known/jwks.json

smartgrid:
  kafka:
    bootstrap-servers: localhost:9092
    schema-registry-url: http://localhost:18081
    group-id: contract-service
  tracing:
    service-name: contract-service
  contract:
    evaluator-interval-ms: 900000
